odow/SDDP.jl

examples/dematos_cutselection.jl
examples/hydro_valley_deterministic.jl
examples/hydro_valley_markov.jl
examples/hydro_valley_stagewise.jl
examples/hydro_valley_stagewise_markov.jl
examples/risk_aversion.jl
examples/visualisation.jl

Fix https://github.com/odow/SDDP.jl/issues/9

Fix hydro examples typo

---

src/utilities.jl
src/valuefunctions.jl

This is too get the iteration number into a solvehook, not super essential.
Using length because before iteration 1 there is no log.

Add iteration keyword

---

README.md
src/avar_riskaversion.jl

Fix AVaR ambiguity

---

examples/simplified_hydrothermal_dispatch.jl
test/examples.jl

This will also test the issue #18

New Simplified Hydrothermal Dispatch example

---

examples/worst_case.jl
src/avar_riskaversion.jl
src/riskmeasures.jl
src/valuefunctions.jl
test/examples.jl
test/riskmeasures.jl

This PR tidies the `modifyprobability!` function.
@lkapelevich this will impact the DRO stuff.

Tidy modifyprobability!

---

examples/newsvendor.jl
src/utilities.jl
test/sddpmodels.jl

The title says it all.
Big things that aren't really tested (from [CodeCov](https://codecov.io/gh/odow/SDDP.jl)):

Add more tests to improve coverage

---

examples/asset_management_stagewise.jl
examples/simple_objective_noise.jl
src/SDDP.jl
src/noises.jl
src/typedefinitions.jl
src/valuefunctions.jl
test/examples.jl
test/noises.jl

@adow031 this should work. Not overly tested for bugs.

Add stagewise noise to objective function

---

src/SDDP.jl
test/sddpmodels.jl
test/utilities.jl

Improve test coverage

---

examples/hydro_valley_deterministic.jl
examples/simple_objective_noise.jl
src/print.jl
src/typedefinitions.jl
src/valuefunctions.jl
src/visualizer/visualize_simulation.jl
src/visualizer/visualize_value_function.jl
test/cutoracles.jl
test/riskmeasures.jl
test/utilities.jl
test/visualization.jl

Even more tests

---

examples/async_newsvendor.jl
src/SDDP.jl
src/solve_asyncronous.jl

Improve Async tests

---

examples/async_newsvendor.jl
src/SDDP.jl
src/solve_asyncronous.jl
src/valuefunctions.jl

Make master write discovered cuts rather than slaves

---

examples/hydro_valley_markov.jl
src/SDDP.jl
src/utilities.jl
test/dispatch.jl
test/runtests.jl

WIP: add triangular dispatch

---

examples/vehicle_location.jl
test/examples.jl

Add vehicle location problem

---

examples/StochDynamicProgramming.jl/multistock-example.jl
examples/StochDynamicProgramming.jl/stock-example.jl
examples/StochasticDualDynamicProgramming.jl/prob5.2_2stages.jl
examples/StochasticDualDynamicProgramming.jl/prob5.2_3stages.jl
examples/async_newsvendor.jl
examples/newsvendor_historic_simulation.jl
src/simulate.jl

Enable pmap for simulations

---

src/JuMPfunctions.jl
src/SDDP.jl
src/utilities.jl

This PR adds a new method `jumpsolve` as a work around for https://github.com/JuliaOpt/JuMP.jl/issues/1110

Modify JuMP.solve 

---

src/SDDP.jl

As requested by @adow031 for his research code.
Will add proper testing and documentation when research codes are merged.

Time-varying value functions

---

examples/Agriculture/mccardle_farm.jl
src/SDDP.jl

Since @adow031 is going to complain until this is done.
Closes #63

Stage dependent objective bound

---

src/utilities.jl

For help debugging numerical issues such as those raised in #6

Write offending files to MPS for analysis

---

src/deprecate.jl
src/solve_asyncronous.jl

fix writeaynccut! spelling

---

examples/Newsvendor/async_newsvendor.jl
src/simulate.jl

pmap simulations without copying every time

---

src/visualizer/visualize_simulation.jl

Overload Base.show

---

src/defaultvaluefunction.jl
src/deprecate.jl
src/solve_asyncronous.jl
src/utilities.jl

Fix bug writing price interpolation cuts to file in asyncronous mode

---

examples/Conic/simple_conic.jl
src/typedefinitions.jl

Add conic example but don't test as Clp doesn't support.

---

REQUIRE
examples/PriceInterpolation/widget_thesis_example.jl
src/visualizer/publication_plots.jl
src/visualizer/visualize.jl
test/visualization.jl

This makes figures like
It seems like this should be tested with `RecipesBase.apply_recipe` (ref https://discourse.julialang.org/t/how-to-test-plot-recipes/2648).

Add publicationplot recipe

---

examples/PriceInterpolation/simple_markov.jl
test/examples.jl

Addresses https://github.com/odow/SDDP.jl/issues/121#issuecomment-383442726
Prices increase in Markov state 2, and decrease in Markov state 1.

Example showing price markov

---

examples/HydroValleys/simplified_hydrothermal_dispatch.jl
src/simulate.jl

It can be interesting to save dual variables to get marginal costs for some resources.

Allow users to save dual variables during simulation

---

src/utilities.jl
test/utilities.jl

Change writeMPS to writeLP

---

src/cut_oracles/LevelOneCutOracle.jl

It now uses Julia structs to store information instead of lots of vectors.
It also checks to see if the state has been previously visited.
I haven't tested for performance but I don't think it's much of a change.
We might lose some speed checking for prior states, but we might gain 
some from only storing unique states.

Re-write Level One cut selection in a much better format.

---

docs/src/apireference.md
docs/src/tutorial/03_objective_noise.md
examples/AssetManagement/asset_management_stagewise.jl
examples/Newsvendor/newsvendor.jl
examples/PriceInterpolation/widget_thesis_example.jl
src/SDDP.jl
src/deprecate.jl
src/solve_asynchronous.jl
src/typedefinitions.jl
src/utilities.jl

(1) rename BoundConvergence to BoundStalling; and
(2) fix the definition of the convergence test so that it aligns with
the definition as given in my thesis.
Fixes #131

Fix bound stalling stopping rule.

---

docs/src/apireference.md
docs/src/tutorial/12_price_interpolation.md
docs/src/tutorial/13_constraint_noise.md
src/SDDP.jl
src/experimental.jl

Developed after hacking with @Thuener 
Largely un-tested and under-development.

Add experimental (hacky) support for noise in the constraint matrix.

---

docs/src/tutorial/01_first_steps.md
docs/src/tutorial/08_odds_and_ends.md

Few more docs

---

docs/src/tutorial/08_odds_and_ends.md

Clarify that multiple RHS noises are not sampled independently

---

docs/src/apireference.md
docs/src/tutorial/06_cut_selection.md
src/cut_oracles/DefaultCutOracle.jl
src/cut_oracles/LevelOneCutOracle.jl
src/cut_oracles/cutoracles.jl
src/defaultvaluefunction.jl
src/price_interpolation/dynamic_price_interpolation.jl
src/price_interpolation/dynamic_price_interpolation_oracle.jl
src/price_interpolation/static_price_interpolation.jl
src/utilities.jl
src/visualizer/visualize_value_function.jl
test/cutoracles.jl

I'm about to embark on a large re-write of this library. As part of that, I will be updating the code to be much more readable. As such, SDDP.jl will be adopting the [JuMP style guide](http://www.juliaopt.org/JuMP.jl/latest/style.html).

Cut oracle style fixes

---

docs/src/tutorial/07_plotting.md

Adds example to address #168.
@Thuener is this sufficient?

Add more docs on publicationplot

---

docs/src/apireference.md
src/algorithm.jl
src/plugins/bellman_functions.jl
src/plugins/headers.jl

Add cut_deletion_minimum to train

---

Manifest.toml
docs/make.jl
docs/src/apireference.md
docs/src/tutorial/01_first_steps.md
docs/src/tutorial/07_advanced_modelling.md
docs/src/tutorial/08_debugging.md
src/algorithm.jl
src/print.jl
src/user_interface.jl

Add a debugging tutorial

---

src/user_interface.jl

Add extension dictionaries for extensions

---

examples/belief.jl
examples/partially_observable_paper.jl
src/user_interface.jl
test/user_interface.jl

Refactor passing of lipschitz values for belief

---

examples/sldp_example_one.jl

The lower bound now matches the one in the paper (the convex problem is
solved to optimality)

Fix absolute value representation and update bound

---

src/algorithm.jl
test/algorithm.jl

Fix a bug that slipped into #215.
Thanks to @Thuener for catching it.

[bug] fix bug in modify_similar_nodes

---

src/SDDP.jl

Ref https://github.com/JuliaPlots/RecipesBase.jl/pull/55

Implement work-around for bug in RecipesBase

---

examples/tiger_problem.jl
src/algorithm.jl
src/plugins/stopping_rules.jl
src/visualization/dashboard.jl

Credit to @peraaslid for reporting.
Closes #231

Fix a number of issues with too few iterations in the log

---

docs/src/tutorial/01_first_steps.jl
docs/src/tutorial/05_plotting.jl

Add explanation of do syntax in docs

---

.travis.yml
Project.toml
docs/Project.toml
src/SDDP.jl
src/plugins/integrality_handlers.jl
test/algorithm.jl
test/deterministic_equivalent.jl
test/plugins/backward_sampling_schemes.jl
test/plugins/bellman_functions.jl
test/plugins/integrality_handlers.jl
test/plugins/risk_measures.jl
test/plugins/sampling_schemes.jl
test/plugins/stopping_rules.jl
test/runtests.jl
test/user_interface.jl
test/visualization.jl

It's about time we finally registered this as a proper package with tagged versions.

Update Project.toml and using's for registration

---

src/user_interface.jl
test/user_interface.jl

Provide better error messages in PolicyGraph when providing bounds

---

Project.toml

Bump minimum HTTP version

---

docs/src/guides/create_a_general_policy_graph.md

Add documentation on simulating non-standard policy graphs

---

src/user_interface.jl

Improve docs for MarkovianPolicyGraph

---

src/algorithm.jl

cc @haoxiangyang89
A recent change of MOI/Gurobi must have exposed this with Gurobi. We should check for primal feasibility before asking for the variable value.

Move test for primal feasibility earlier

---

examples/StochDynamicProgramming.jl_multistock.jl
examples/agriculture_mccardle_farm.jl
examples/air_conditioning.jl
examples/asset_management_simple.jl
examples/booking_management.jl
examples/complicated_hydro.jl
examples/generation_expansion.jl
examples/hydro_valley.jl
examples/infinite_horizon/ball_on_beam.jl
examples/infinite_horizon/powder.jl
examples/inventory_management.jl
examples/paper_models/ddb_2018.jl
examples/vehicle_location.jl
src/algorithm.jl
src/deterministic_equivalent.jl
src/plugins/bellman_functions.jl
src/plugins/parallel_schemes.jl
src/visualization/value_functions.jl
test/algorithm.jl
test/user_interface.jl

Add option to use different logging frequency

---

src/plugins/parallel_schemes.jl
test/plugins/parallel_schemes.jl

Closes #324
So this was an oversight...
cc @adow031

Implement async price and belief interpolations

---

src/algorithm.jl
src/user_interface.jl
test/algorithm.jl

Closes #329.
We should really implement #268 and #269 as well.

Add a numerical recovery function

---

Project.toml
docs/src/apireference.md
src/Experimental.jl
src/JuMP.jl
src/SDDP.jl
test/Experimental.jl

This PR implements a reader and writer for [StochOptFormat](https://odow.github.io/StochOptFormat/).
It is still very much experimental and a work-in-progress, but it works!
TODOs
cc @joaquimg

Implement StochOptFormat

---

Project.toml
docs/src/apireference.md
src/Experimental.jl
test/Experimental.jl

Add TestScenarios and evaluate

---

docs/src/guides/add_a_risk_measure.md
src/plugins/risk_measures.jl
test/plugins/risk_measures.jl

Paper: http://www.optimization-online.org/DB_HTML/2020/08/7984.html
@joaquimg can finally release this!

Add entropic risk measure

---

docs/src/examples/the_farmers_problem.jl
docs/src/index.md
docs/src/tutorial/06_warnings.jl
src/algorithm.jl
src/user_interface.jl

Found a few typos while reading through docs and code

Minor typos

---

docs/make.jl
docs/src/tutorial/01_first_steps.jl
docs/src/tutorial/21_theory_intro.jl

Address Bernardo's comments. Still a few things to fix from his notes.

[docs] Refinements of the theory tutorial

---

docs/Project.toml
docs/src/tutorial/21_theory_intro.jl
docs/src/tutorial/22_risk.jl

https://odow.github.io/SDDP.jl/previews/PR369/tutorial/22_risk

Add a tutorial on risk aversion

---

src/algorithm.jl
test/algorithm.jl

Add option to simulate with different incoming state

---

src/plugins/bellman_functions.jl
test/runtests.jl

Part of #268
We could consider an option to skip adding the cut.

Add warning when adding cuts with high dynamic range

---

src/algorithm.jl
src/print.jl

Add problem statistics in header

---

src/visualization/publication_plot.jl
src/visualization/spaghetti_plot.jl

Relax visualization requirements

---

docs/src/guides/acess_previous_variables.md

Add docs on accessing previous stage

---

docs/src/tutorial/01_first_steps.jl
src/visualization/value_functions.jl

Expand docs for water values

---

src/user_interface.jl
test/user_interface.jl

Sanitize inputs to stageobjective macro

---

src/user_interface.jl
test/user_interface.jl

Check feasibility of initial point

---

docs/src/guides/choose_a_stopping_rule.md
src/plugins/stopping_rules.jl
test/plugins/stopping_rules.jl

Add StoppingChain

---

Project.toml
docs/src/guides/simulate_using_a_different_sampling_scheme.md
src/plugins/sampling_schemes.jl

Closes #414 
I didn't run the tests locally. Let's see what breaks...

Allow Historical to sample sequentially

---

src/algorithm.jl

Add warning when training with existing cuts

---

docs/src/apireference.md
docs/src/examples/the_farmers_problem.jl
docs/src/examples/vehicle_location.jl
src/plugins/bellman_functions.jl
test/plugins/bellman_functions.jl

Add add_all_cuts

---

src/algorithm.jl
src/print.jl

Display more attributes of a model

---

.github/workflows/documentation.yml
docs/src/examples/air_conditioning.jl
docs/src/examples/the_farmers_problem.jl
docs/src/tutorial/basic/01_first_steps.jl
docs/src/tutorial/basic/03_objective_uncertainty.jl
docs/src/tutorial/basic/06_warnings.jl

Fix dollar escaping in docs

---

docs/src/guides/simulate_using_a_different_sampling_scheme.md

[docs] fix documentation of Historical sampling scheme

---

docs/src/tutorial/basic/01_first_steps.jl
docs/src/tutorial/basic/06_warnings.jl

[docs] add relatively complete recourse section

---

docs/src/apireference.md
docs/src/examples/air_conditioning.jl
docs/src/examples/booking_management.jl
docs/src/examples/generation_expansion.jl
docs/src/examples/vehicle_location.jl
docs/src/guides/add_integrality.md
src/algorithm.jl
src/plugins/duality_handlers.jl
src/plugins/headers.jl
test/plugins/duality_handlers.jl
test/plugins/forward_passes.jl

Better names and better theory documentation.

Rename ConicDuality and relax_integrality

---

src/plugins/duality_handlers.jl
test/plugins/duality_handlers.jl

@haoxiangyang89, not sure why I didn't try this before.

Add a second solve to find a sparse dual vector

---

docs/src/examples/biobjective_hydro.jl
src/SDDP.jl
src/biobjective.jl

Add a biobjective solver

---

src/algorithm.jl
test/plugins/forward_passes.jl

This came in handy for https://github.com/odow/SDDP.jl/issues/429#issuecomment-903190148
It lets you build visualization tools for the forward pass.

Add forward_pass_callback

---

src/plugins/bellman_functions.jl
src/plugins/cuts.schema.json
test/plugins/bellman_functions.jl

Closes #360 
Still needs some tests. 
@adow031, your [hack](https://github.com/odow/SDDP.jl/issues/360#issuecomment-912874789) isn't quite correct. It'll lead to cuts being added with the wrong intercept.

Save states in write_cuts_to_file

---

docs/src/tutorial/basic/02_arma.jl
docs/src/tutorial/basic/07_arma.jl

[docs] add auto-regressive tutorial

---

Project.toml

Part of https://github.com/jump-dev/JuMP.jl/issues/2564

Update to JuMP 1.0

---

docs/src/examples/air_conditioning.jl

Substituted with a Wayback Machine link

Fix broken link in air conditioning example

---

src/plugins/sampling_schemes.jl
test/plugins/sampling_schemes.jl

Add support for initial_node in InSampleMonteCarlo and OutOfSampleMonteCarlo

---

src/algorithm.jl

Save cuts before throwing error

---

.gitignore
docs/make.jl
docs/src/changelog.md

Preview: https://odow.github.io/SDDP.jl/previews/PR536/release_notes/

Add a changelog

---

src/visualization/dashboard.html
src/visualization/dashboard.jl

Fix re-use of dashboard between solves

---

src/user_interface.jl
test/user_interface.jl

Fix error on inconsistent input to add_objective_state

---

src/plugins/duality_handlers.jl

Closes #548
An alternative to the reverted #531 (cc @bfpc)

Try to recover if we need a dual solution and experienced numerical issues

---

Project.toml
docs/src/changelog.md

Prep for v0.4.8

---

docs/make.jl
docs/src/apireference.md
docs/src/tutorial/mdps.jl
src/user_interface.jl

Part of #496
x-ref #513
x-ref #505
cc @bernardokp

[docs] add tutorial on Markov Decision Processes

---

docs/src/tutorial/arma.jl
docs/src/tutorial/objective_states.jl

[docs] fixes to ARMA and objective state tutorials

---

src/plugins/parallel_schemes.jl
test/plugins/parallel_schemes.jl

Add support for passing optimizer to Asynchronous

---

docs/src/guides/improve_computational_performance.md

I don't know why, but this seemed to fix the problem for me. 
Closes https://github.com/odow/SDDP.jl/issues/417

[docs] update how to initialize parallel scheme

---

Project.toml
docs/src/changelog.md

Prep for v1.0.0

---

docs/src/changelog.md
docs/src/index.md

https://odow.github.io/SDDP.jl/previews/PR580/

[docs] minor documentation updates

---

docs/src/guides/add_integrality.md

[docs] clarify integrality limitations

---

src/plugins/parallel_schemes.jl

x-ref https://github.com/odow/SDDP.jl/pull/579
cc @rafabench

Flush logs every iteration

---

src/algorithm.jl
src/plugins/parallel_schemes.jl
src/print.jl
src/user_interface.jl
test/algorithm.jl
test/plugins/parallel_schemes.jl
test/plugins/stopping_rules.jl

Add numerical issues to log

---

docs/src/tutorial/first_steps.jl
src/print.jl
test/algorithm.jl
test/user_interface.jl

https://odow.github.io/SDDP.jl/previews/PR588/tutorial/first_steps/#Training-a-policy

Tweak printing of the log

---

Project.toml
src/Experimental.jl
test/Experimental.jl
test/electric.sof.json

x-ref https://github.com/odow/StochOptFormat/pull/25

[StochOptFormat] update to v0.3

---

src/MSPFormat.jl
test/MSPFormat.jl

Found via https://github.com/odow/SDDP.jl/issues/603

[MSPFormat] fix parsing of random terms

---

Project.toml
docs/src/changelog.md

Prep for v1.5.0

---

docs/src/guides/access_previous_variables.md

[docs] fix bugs in access_previous_variables.md

---

docs/src/tutorial/example_milk_producer.jl
docs/src/tutorial/mdps.jl
docs/src/tutorial/objective_states.jl
src/algorithm.jl
src/plugins/parallel_schemes.jl

https://odow.github.io/SDDP.jl/previews/PR620

Change default logging frequency

---

docs/src/apireference.md
src/plugins/stopping_rules.jl
test/plugins/stopping_rules.jl

Add FirstStageStoppingRule

---

docs/make.jl
docs/src/tutorial/decision_hazard.jl
docs/styles/Vocab/SDDP-Vocab/accept.txt

Closes #628 
cc @hghayoom I elaborated on our example somewhat. There's an additional complication concerning the first-stage decision, but this is often unneeded if your first-stage is already deterministic.

[docs] add Here-and-now decisions tutorial

---

src/plugins/sampling_schemes.jl

[docs] clarify OutOfSampleMonteCarlo for deterministic nodes

---

src/JuMP.jl

Fix set_optimizer for models read from file

---

docs/src/explanation/theory_intro.jl

@sigmundholm does this make it clearer? Suggestions for changes?
Closes #648
Here's the preview link: https://odow.github.io/SDDP.jl/previews/PR651/explanation/theory_intro/#Preliminaries:-approximating-the-cost-to-go-term

[docs] clarify what a subgradient and reduced cost are

---

docs/src/tutorial/example_reservoir.jl

I'm giving a few tutorials in October at https://cermics-lab.enpc.fr/seso2023/ and https://julia-users-paris.github.io/workshop/en/.
My plan is to work through a few of these examples, with little exercises at the bottom for people to try.
Preview: https://odow.github.io/SDDP.jl/previews/PR659/tutorial/example_reservoir/
x-ref #658

[docs] update deterministic to stochastic example

---

docs/src/tutorial/example_milk_producer.jl

https://odow.github.io/SDDP.jl/previews/PR660/tutorial/example_milk_producer/

[docs] simplify milk producer example

---

src/algorithm.jl
test/algorithm.jl

Throw error for invalid log_frequency values

---

.github/workflows/static.yml

This is a bit of an experiment for https://github.com/jump-dev/JuMP.jl/issues/3479

Create static.yml for deploying GitHub pages

---

docs/src/examples/FAST_hydro_thermal.jl
docs/src/guides/debug_a_model.md
src/deterministic_equivalent.jl
test/deterministic_equivalent.jl

Fix support for objective_sense in deterministic_equivalent

---

.github/workflows/documentation.yml

x-ref https://github.com/JuliaDocs/Documenter.jl/issues/2278

[docs] re-add GITHUB_TOKEN

---

src/modeling_aids.jl
src/user_interface.jl
test/modeling_aids.jl

Fix duplicate nodes in MarkovianGraph

---

src/plugins/stopping_rules.jl

A slight rant on why this is not a good stopping rule.

Add warning to Statistical stopping rule

---

docs/src/guides/simulate_using_a_different_sampling_scheme.md

[docs] clarify simulate using a different sampling scheme

---

docs/src/guides/choose_a_stopping_rule.md

[docs] update choose_a_stopping_rule.md

---

src/MSPFormat.jl

Fix non-constant state dimension in MSPFormat reader

---

src/algorithm.jl
src/plugins/duality_handlers.jl

Support NEARLY_FEASIBLE_POINT

---

docs/src/tutorial/first_steps.jl

Closes #746
@dannyopts what do you think of this? Any suggestions for improvements?
p.s., you can suggest edits to the documentation by clicking the "Edit source on GitHub" button:
and then clicking the pencil:

[docs] clarify monotonicity of bound in first_steps.jl

---

test/plugins/threaded.jl

x-ref https://github.com/jump-dev/JuMP.jl/pull/3799

Skip threading tests if running in serial

---

src/MSPFormat.jl
test/MSPFormat.jl

Improve error for lagged state variables in MSPFormat

---

src/visualization/publication_plot.jl
test/visualization/visualization.jl

This fixes an issue in Bernardo's code.

Support publication plot with replications of different lengths

---

docs/src/apireference.md
src/algorithm.jl
src/plugins/duality_handlers.jl
test/algorithm.jl

Add a callback to modify the subproblem on numerical difficulty

---

docs/make.jl
docs/src/guides/add_a_custom_cut.md

Someone asked me this over email

[docs] add Add a custom cut guide

---

docs/make.jl
docs/src/tutorial/batteries.jl
docs/styles/Vocab/SDDP-Vocab/accept.txt

Preview: https://sddp.dev/previews/PR849/tutorial/batteries/

[docs] add batteries tutorial from winter school

---

src/plugins/duality_handlers.jl

http://sddp.dev/previews/PR861

Remove near zeros in LagrangianDuality

---

src/algorithm.jl

Improve performance of computing the stage objective value
